# Generated by Django 6.0.5 on 2026-05-06 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('mood', models.CharField(choices=[('Grief', 'Grief'), ('Nostalgia', 'Nostalgia'), ('Regret', 'Regret'), ('Hope', 'Hope'), ('Rage', 'Rage'), ('Peace', 'Peace'), ('Reflection', 'Reflection')], max_length=20)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
